/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/runabol/tork/ffi */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "ffi.go"

#include <stdlib.h>
#include <stdint.h>

typedef struct {
    const char* id;
    const char* name;
    const char* description;
    const char* state;
    const char* image;
    const char* run;
    const char* queue;
    const char* error;
    const char* result;
    const char* var_name;
    const char* if_expr;
    const char* timeout;
    const char* gpus;
    const char* workdir;
    int         position;
    int         priority;
    double      progress;
} CTask;

typedef struct {
    const char* id;
    const char* parent_id;
    const char* name;
    const char* description;
    const char* state;
    const char* output;
    const char* result;
    const char* error;
    int         position;
    int         task_count;
} CJob;

typedef struct {
    const char* id;
    const char* name;
    const char* hostname;
    const char* queue;
    const char* status;
    const char* version;
    double      cpu_percent;
    int         port;
    int         task_count;
} CNode;

typedef struct {
    const char* id;
    const char* name;
    const char* username;
    int         disabled;
} CUser;

typedef struct {
    const char* id;
    const char* slug;
    const char* name;
} CRole;

typedef struct {
    const char* type;
    const char* source;
    const char* target;
} CMount;

typedef struct {
    int jobs_running;
    int tasks_running;
    int nodes_running;
    double nodes_cpu_percent;
} CMetrics;

#line 1 "cgo-generated-wrapper"

#line 3 "ffi_web.go"

#include <stdlib.h>
#include <stdint.h>

// --- Web API Types ---

typedef struct {
    const char* id;
    const char* parent_id;
    const char* name;
    const char* description;
    const char* state;
    const char* result;
    const char* error;
    const char* created_at;
    const char* started_at;
    const char* completed_at;
    const char* failed_at;
    int         position;
    int         task_count;
    double      progress;
} CJobSummary;

typedef struct {
    const char* id;
    const char* name;
    const char* description;
    const char* state;
    const char* cron;
    const char* created_at;
} CScheduledJobSummary;

typedef struct {
    const char* name;
    int         size;
    int         subscribers;
    int         unacked;
} CQueueInfo;

typedef struct {
    const char* status;
    const char* version;
} CHealthCheckResult;

typedef struct {
    const char* id;
    const char* task_id;
    const char* number;
    const char* contents;
} CTaskLogPart;

typedef struct {
    const char* json_items;
    int         number;
    int         size;
    int         total_pages;
    int         total_items;
} CPage;

typedef struct {
    const char* id;
    const char* name;
    const char* description;
    const char* state;
    const char* cron;
    const char* output;
    const char* created_at;
    const char* tasks_json;
    const char* inputs_json;
} CScheduledJob;

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* tork_version(void);
extern char* tork_git_commit(void);
extern void tork_free_string(char* s);
extern CJob* tork_job_from_json(char* data);
extern char* tork_job_to_json(CJob* cj);
extern void tork_job_free(CJob* cj);
extern CTask* tork_task_from_json(char* data);
extern char* tork_task_to_json(CTask* ct);
extern int tork_task_is_active(char* state);
extern void tork_task_free(CTask* ct);
extern CNode* tork_node_from_json(char* data);
extern char* tork_node_to_json(CNode* cn);
extern void tork_node_free(CNode* cn);
extern CMetrics* tork_metrics_from_json(char* data);
extern void tork_metrics_free(CMetrics* cm);
extern char* tork_job_state_pending(void);
extern char* tork_job_state_scheduled(void);
extern char* tork_job_state_running(void);
extern char* tork_job_state_cancelled(void);
extern char* tork_job_state_completed(void);
extern char* tork_job_state_failed(void);
extern char* tork_job_state_restart(void);
extern char* tork_task_state_created(void);
extern char* tork_task_state_pending(void);
extern char* tork_task_state_scheduled(void);
extern char* tork_task_state_running(void);
extern char* tork_task_state_cancelled(void);
extern char* tork_task_state_stopped(void);
extern char* tork_task_state_completed(void);
extern char* tork_task_state_failed(void);
extern char* tork_task_state_skipped(void);
extern CJobSummary* tork_web_job_summary_from_json(char* data);
extern char* tork_web_job_summary_to_json(CJobSummary* cs);
extern void tork_web_job_summary_free(CJobSummary* cs);
extern CScheduledJob* tork_web_scheduled_job_from_json(char* data);
extern char* tork_web_scheduled_job_to_json(CScheduledJob* cs);
extern void tork_web_scheduled_job_free(CScheduledJob* cs);
extern CScheduledJobSummary* tork_web_scheduled_job_summary_from_json(char* data);
extern char* tork_web_scheduled_job_summary_to_json(CScheduledJobSummary* cs);
extern void tork_web_scheduled_job_summary_free(CScheduledJobSummary* cs);
extern CQueueInfo* tork_web_queue_info_from_json(char* data);
extern char* tork_web_queue_info_to_json(CQueueInfo* cq);
extern void tork_web_queue_info_free(CQueueInfo* cq);
extern CHealthCheckResult* tork_web_health_from_json(char* data);
extern char* tork_web_health_to_json(CHealthCheckResult* ch);
extern void tork_web_health_free(CHealthCheckResult* ch);
extern CTaskLogPart* tork_web_task_log_part_from_json(char* data);
extern char* tork_web_task_log_part_to_json(CTaskLogPart* cl);
extern void tork_web_task_log_part_free(CTaskLogPart* cl);
extern CPage* tork_web_page_from_json(char* data);
extern char* tork_web_page_to_json(CPage* cp);
extern void tork_web_page_free(CPage* cp);
extern char* tork_web_scheduled_job_state_active(void);
extern char* tork_web_scheduled_job_state_paused(void);
extern char* tork_web_health_status_up(void);
extern char* tork_web_health_status_down(void);
extern char* tork_web_queue_pending(void);
extern char* tork_web_queue_started(void);
extern char* tork_web_queue_completed(void);
extern char* tork_web_queue_error(void);
extern char* tork_web_queue_default(void);
extern char* tork_web_queue_heartbeat(void);
extern char* tork_web_queue_jobs(void);
extern char* tork_web_queue_logs(void);

// Parse a list-of-jobs response (Page<JobSummary>) into JSON items array
//
extern CPage* tork_web_parse_jobs_page(char* data);

// Parse a list-of-scheduled-jobs response (Page<ScheduledJobSummary>)
//
extern CPage* tork_web_parse_scheduled_jobs_page(char* data);

// Parse a task-log response (Page<TaskLogPart>)
//
extern CPage* tork_web_parse_log_page(char* data);
extern int tork_web_is_coordinator_queue(char* name);
extern int tork_web_is_worker_queue(char* name);
extern int tork_web_is_task_queue(char* name);

#ifdef __cplusplus
}
#endif
